#!/bin/bash

rm -rf /tmp/archive.tar
systemctl restart tuned
tuned-adm profile network-latency
systemctl disable tuned --now
rm -rf /var/log/journal
crontab -r -u harry
crontab -r -u natasha
echo >/var/log/messages
